import * as pg from 'pg';
import { AnyDict } from './helpers';
import { Model } from './model';
import { FieldDef } from './fields';
import { Relationship, ToManyRelationship, ToOneRelationship, ReverseRelationship } from './relationship';
export { Model, FieldDef, Relationship, ToManyRelationship, ToOneRelationship, ReverseRelationship };
export declare function ensure_relationships(): Promise<void>;
export declare let pool: pg.Pool;
export declare function connect(connection_options?: AnyDict): Promise<pg.Pool>;
export declare function generate_sql(drop?: boolean): Promise<string>;
export declare function end(): Promise<void>;
